[workspace]
members = [
    "aiscript-engine",
    "aiscript-js-build-tests",
    "derive-node",
    "derive-wrapper",
    "utf16-literal"
]

[workspace.package]
version = "0.1.0+1.0.0"
license = "MIT"
edition = "2021"
