[package]
name = "aisenv-engine"
description = "An AiScript Engine written in Rust."
version = "1.0.0+1"
license = "MIT"

edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.93"
