[package]
name = "aiscript-engine"
description = "An AiScript Engine written in Rust."
repository = "https://github.com/takejohn/aisenv-engine"
version = "0.1.0+0.1.0"
license = "MIT"

edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.93"
