[package]
name = "aiscript-engine-types"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
aiscript-engine-ast.workspace = true
aiscript-engine-common.workspace = true
derive-wrapper.workspace = true
utf16-literal.workspace = true
