[package]
name = "aiscript-engine-lexer"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
aiscript-engine-common.workspace = true
utf16-literal.workspace = true
