[package]
name = "aiscript-js-build-tests"
version.workspace = true
edition.workspace = true

[lib]

[dependencies]

[dev-dependencies]
aiscript-engine.path = "../aiscript-engine"
pretty_assertions = "1.4.1"
serde_json = "1.0.128"
