[package]
name = "aiscript-engine-values"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
aiscript-engine-common.workspace = true
gc.workspace = true
indexmap.workspace = true
utf16-literal.workspace = true
