[package]
name = "aiscript-engine-common"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
utf16-literal.path = "../utf16-literal"
