[package]
name = "aiscript-engine-common"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
utf16-literal.workspace = true
